### ISSUE TITLE
Can you Add SoftAES support?

### ISSUE THREAD

**Issue by shinesli** [shyba/aeon-stak-cpu#11]
Hi, I'm running xmr-stak-cpu fine with current setup. But with aeon, I'm getting "Illegal instruction ". Is that because of the missing softaes support in this code?

**Comment by shyba** [comment]
Should happen only on "low_power". Are you using it?
For the other modes, it should work fine. You can check this on your configuration.
I am rebasing and will try to fix soft_aes for low_power.

Thank you for reporting!

**Comment by shinesli** [comment]
Yes, that's exactly what I'm using. Thank you and hope to see that got fixed soon!
