### ISSUE TITLE
floating point error on FreeBSD 11.1

### ISSUE THREAD

**Issue by lisergey** [shyba/aeon-stak-cpu#14]
I've compiled aeon-stak-cpu under FreeBSD 11.1 and set up config.
Run it and from time to time get errors like "segmentation fault" and "floating point operation error", but after third try it starts. That is strange.

What to check and where to look to find the cause?
On other FreeBSD machines with different CPUs it runs well.

**Comment by lisergey** [comment]
looks like the probable cause is hwloc trying to do its job:
if segfault, then it stops right after 
[2017-09-28 12:09:28] : Connecting to pool pool.aeonmining.pro:3333 ...

but after several attempts it gets over with
[2017-09-28 12:09:28] : hwloc: can't bind memory

I'll try to compile without hwloc on this machine to see if it would matter.

**Comment by shyba** [comment]
Recompiling solved it? Which CPU is that?

**Comment by lisergey** [comment]
yes, it solved. it still complains but works:
...
[2017-10-16 12:36:23] : hwloc: can't bind memory
[2017-10-16 12:36:23] : hwloc: can't bind memory
...

# ldd ~miner/aeon-stak-cpu.nomicrohttpd 
/home/miner/aeon-stak-cpu.nomicrohttpd:
        libthr.so.3 => /lib/libthr.so.3 (0x800853000)
        libssl.so.8 => /usr/lib/libssl.so.8 (0x800a7b000)
        libcrypto.so.8 => /lib/libcrypto.so.8 (0x800e00000)
        libc++.so.1 => /usr/lib/libc++.so.1 (0x801269000)
        libcxxrt.so.1 => /lib/libcxxrt.so.1 (0x801530000)
        libm.so.5 => /lib/libm.so.5 (0x80174e000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x801979000)
        libc.so.7 => /lib/libc.so.7 (0x801b87000)

OS: 11.1-RELEASE-p1
CPU: CPU: Intel(R) Atom(TM) CPU N570   @ 1.66GHz (1664.84-MHz K8-class CPU)

thank you for nice miner!
