### ISSUE TITLE
Invalid config file. Your CPU config array has 1 members, while you want to use 2 threads.

### ISSUE THREAD

**Issue by con2000** [shyba/aeon-stak-cpu#2]
I'm confused why it's saying this. my computer has 2 physical cores. 
I put my config file here ( https://pastebin.com/btyG4gub )
If you need anymore information let me know

**Comment by stoffu** [comment]
Because you provided only one line in `cpu_threads_conf`:

    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },

while specifying thread num as 2. Provide a line for each thread, like:

    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },

The last `affine_to_cpu` could be all set to `false`.

**Comment by con2000** [comment]
Thanks dude, sorry I didnt understand
